runtime: python39

# entrypoint: gunicorn -b :$PORT core.wsgi:application #webサーバ
entrypoint: gunicorn -b :$PORT main:app #webサーバ

resources:
  memory_gb: 4

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto