# Generated by Django 4.1.7 on 2023-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('career', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('uniformNumber', models.IntegerField()),
                ('birthPlace', models.CharField(max_length=10)),
                ('handed', models.CharField(max_length=5)),
                ('bbox', models.CharField(max_length=5)),
                ('contact', models.IntegerField()),
                ('power', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('steeling', models.IntegerField()),
                ('arm_strength', models.IntegerField()),
                ('arm_accuracy', models.IntegerField()),
                ('catch', models.IntegerField()),
                ('reaction', models.IntegerField()),
                ('profile', models.IntegerField()),
            ],
        ),
    ]
