# Generated by Django 4.1.7 on 2023-03-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004_alter_player_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player',
            new_name='players',
        ),
    ]
