# Generated by Django 4.1.7 on 2023-03-30 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0007_alter_players_birthplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="age",
            field=models.IntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(55),
                ],
            ),
        ),
    ]
