# Generated by Django 4.1.7 on 2023-04-01 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0008_alter_players_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="slug",
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="players",
            name="arm_accuracy",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="arm_strength",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="catch",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="contact",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="power",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="profile",
            field=models.TextField(default="がんばります！"),
        ),
        migrations.AlterField(
            model_name="players",
            name="reaction",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="speed",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="steeling",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
