# Generated by Django 4.1.7 on 2023-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0009_players_slug_alter_players_arm_accuracy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="slug",
            field=models.SlugField(),
        ),
    ]
