# Generated by Django 4.1.7 on 2023-04-02 07:59

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0010_alter_players_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="slug",
            field=models.SlugField(default=builtins.id, max_length=20),
        ),
    ]
