# Generated by Django 4.1.7 on 2023-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0013_alter_players_birthplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="bbox",
            field=models.CharField(
                choices=[("右打ち", "右打ち"), ("左打ち", "左打ち"), ("両打ち", "両打ち")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="handed",
            field=models.CharField(
                choices=[("右投げ", "右投げ"), ("左投げ", "左投げ")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
