# Generated by Django 4.1.7 on 2023-05-04 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("lastName", models.CharField(max_length=10, verbose_name="姓")),
                ("firstName", models.CharField(max_length=10, verbose_name="名")),
                (
                    "career",
                    models.CharField(
                        choices=[
                            ("高卒", "高卒"),
                            ("大卒", "大卒"),
                            ("社会人", "社会人"),
                            ("助っ人", "助っ人"),
                        ],
                        default="高卒",
                        max_length=12,
                        verbose_name="経歴",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        default=18,
                        validators=[
                            django.core.validators.MaxValueValidator(40),
                            django.core.validators.MinValueValidator(18),
                        ],
                        verbose_name="入団時の年齢",
                    ),
                ),
                (
                    "number_of_years",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="プロ年数",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        default=180,
                        validators=[
                            django.core.validators.MaxValueValidator(220),
                            django.core.validators.MinValueValidator(150),
                        ],
                        verbose_name="身長",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MaxValueValidator(130),
                            django.core.validators.MinValueValidator(50),
                        ],
                        verbose_name="体重",
                    ),
                ),
                (
                    "uniformNumber",
                    models.SmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(999),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="背番号",
                    ),
                ),
                (
                    "birthPlace",
                    models.CharField(
                        choices=[
                            ("北海道", "北海道"),
                            ("青森県", "青森県"),
                            ("岩手県", "岩手県"),
                            ("宮城県", "宮城県"),
                            ("秋田県", "秋田県"),
                            ("山形県", "山形県"),
                            ("福島県", "福島県"),
                            ("茨城県", "茨城県"),
                            ("栃木県", "栃木県"),
                            ("群馬県", "群馬県"),
                            ("埼玉県", "埼玉県"),
                            ("千葉県", "千葉県"),
                            ("東京都", "東京都"),
                            ("神奈川県", "神奈川県"),
                            ("新潟県", "新潟県"),
                            ("富山県", "富山県"),
                            ("石川県", "石川県"),
                            ("福井県", "福井県"),
                            ("山梨県", "山梨県"),
                            ("長野県", "長野県"),
                            ("岐阜県", "岐阜県"),
                            ("静岡県", "静岡県"),
                            ("愛知県", "愛知県"),
                            ("三重県", "三重県"),
                            ("滋賀県", "滋賀県"),
                            ("京都府", "京都府"),
                            ("大阪府", "大阪府"),
                            ("兵庫県", "兵庫県"),
                            ("奈良県", "奈良県"),
                            ("和歌山県", "和歌山県"),
                            ("鳥取県", "鳥取県"),
                            ("島根県", "島根県"),
                            ("岡山県", "岡山県"),
                            ("広島県", "広島県"),
                            ("山口県", "山口県"),
                            ("徳島県", "徳島県"),
                            ("香川県", "香川県"),
                            ("愛媛県", "愛媛県"),
                            ("高知県", "高知県"),
                            ("福岡県", "福岡県"),
                            ("佐賀県", "佐賀県"),
                            ("長崎県", "長崎県"),
                            ("熊本県", "熊本県"),
                            ("大分県", "大分県"),
                            ("宮崎県", "宮崎県"),
                            ("鹿児島県", "鹿児島県"),
                            ("沖縄県", "沖縄県"),
                            ("台湾", "台湾"),
                            ("キューバ", "キューバ"),
                            ("イタリア", "イタリア"),
                            ("パナマ", "パナマ"),
                            ("韓国", "韓国"),
                            ("オーストラリア", "オーストラリア"),
                            ("中国", "中国"),
                            ("チェコ共和国", "チェコ共和国"),
                            ("アメリカ", "アメリカ"),
                            ("メキシコ", "メキシコ"),
                            ("コロンビア", "コロンビア"),
                            ("カナダ", "カナダ"),
                            ("イギリス", "イギリス"),
                            ("プエルトリコ", "プエルトリコ"),
                            ("ドミニカ共和国", "ドミニカ共和国"),
                            ("イスラエル", "イスラエル"),
                            ("ニカラグア", "ニカラグア"),
                        ],
                        default="東京都",
                        max_length=10,
                        verbose_name="出身地",
                    ),
                ),
                (
                    "throw",
                    models.CharField(
                        choices=[("right", "右"), ("left", "左"), ("both", "両")],
                        default="右",
                        max_length=5,
                        verbose_name="利き腕",
                    ),
                ),
                (
                    "bbox",
                    models.CharField(
                        choices=[("right", "右"), ("left", "左"), ("both", "両")],
                        default="右",
                        max_length=5,
                        verbose_name="打席",
                    ),
                ),
                (
                    "player_type",
                    models.CharField(
                        choices=[("投手", "投手"), ("野手", "野手"), ("二刀流", "二刀流")],
                        default="投手",
                        max_length=3,
                        verbose_name="選手タイプ",
                    ),
                ),
                (
                    "character",
                    models.CharField(
                        choices=[
                            ("ふつう", "ふつう"),
                            ("内気", "内気"),
                            ("熱血", "熱血"),
                            ("お調子者", "お調子者"),
                            ("しっかり者", "しっかり者"),
                            ("クール", "クール"),
                            ("天然", "天然"),
                            ("したたか", "したたか"),
                            ("職人肌", "職人肌"),
                        ],
                        default="ふつう",
                        max_length=10,
                        verbose_name="キャラクター",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/images/image001.png",
                        upload_to="media/images/",
                        verbose_name="見た目",
                    ),
                ),
                (
                    "profile",
                    models.TextField(
                        default="がんばります！！", max_length=150, verbose_name="プロフィール"
                    ),
                ),
                (
                    "pitching_form",
                    models.CharField(
                        choices=[
                            ("オーバースロー", "オーバースロー"),
                            ("スリークォーター", "スリークォーター"),
                            ("サイドスロー", "サイドスロー"),
                            ("アンダースロー", "アンダースロー"),
                        ],
                        default="オーバースロー",
                        max_length=20,
                        verbose_name="投球フォーム",
                    ),
                ),
                (
                    "stamina",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="スタミナ",
                    ),
                ),
                (
                    "maximum_ball_speed",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MaxValueValidator(175),
                            django.core.validators.MinValueValidator(100),
                        ],
                        verbose_name="最大球速",
                    ),
                ),
                (
                    "power_of_straight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ストレートの球威",
                    ),
                ),
                (
                    "growth_of_straight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ストレートのノビ",
                    ),
                ),
                (
                    "control_of_straight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ストレートのコントロール",
                    ),
                ),
                (
                    "mental_strength",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="メンタル",
                    ),
                ),
                (
                    "strike_out",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(5),
                        ],
                        verbose_name="奪三振",
                    ),
                ),
                (
                    "contact",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ミート",
                    ),
                ),
                (
                    "power",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="パワー",
                    ),
                ),
                (
                    "vision",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="選球眼",
                    ),
                ),
                (
                    "speed",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="走力",
                    ),
                ),
                (
                    "arm_strength",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="肩力",
                    ),
                ),
                (
                    "arm_accuracy",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="送球",
                    ),
                ),
                (
                    "reaction",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="打球反応",
                    ),
                ),
                (
                    "catch",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="捕球精度",
                    ),
                ),
                (
                    "main_position",
                    models.CharField(
                        choices=[
                            ("キャッチャー", "キャッチャー"),
                            ("ファースト", "ファースト"),
                            ("セカンド", "セカンド"),
                            ("サード", "サード"),
                            ("ショート", "ショート"),
                            ("レフト", "レフト"),
                            ("センター", "センター"),
                            ("ライト", "ライト"),
                        ],
                        default="キャッチャー",
                        max_length=12,
                        verbose_name="メインポジション",
                    ),
                ),
                (
                    "catcher_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="キャッチャー適正",
                    ),
                ),
                (
                    "first_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="ファースト適正",
                    ),
                ),
                (
                    "second_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="セカンド適正",
                    ),
                ),
                (
                    "third_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="サード適正",
                    ),
                ),
                (
                    "shortstop_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="ショート適正",
                    ),
                ),
                (
                    "left_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="レフト適正",
                    ),
                ),
                (
                    "center_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="センター適正",
                    ),
                ),
                (
                    "right_appropriate",
                    models.CharField(
                        choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                        default="×",
                        max_length=10,
                        verbose_name="ライト適正",
                    ),
                ),
                (
                    "chance",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="チャンス",
                    ),
                ),
                (
                    "vs_left_pitcher",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="対左投手",
                    ),
                ),
                (
                    "inside",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="インコース",
                    ),
                ),
                (
                    "outside",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="アウトコース",
                    ),
                ),
                (
                    "high_ball",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ハイボール",
                    ),
                ),
                (
                    "low_ball",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ローボール",
                    ),
                ),
                (
                    "bunt",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="バント",
                    ),
                ),
                (
                    "base_running",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="走塁",
                    ),
                ),
                (
                    "steeling",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="盗塁",
                    ),
                ),
                (
                    "pitcher_lead",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="投手リード",
                    ),
                ),
                (
                    "home_block",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ブロック",
                    ),
                ),
                (
                    "sturdiness",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="ケガしにくさ",
                    ),
                ),
                (
                    "good_cnt",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="いいね",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
