# Generated by Django 4.1.7 on 2023-04-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="center_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="センター適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="left_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="レフト適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="main_position",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="キャッチャー",
                max_length=12,
                verbose_name="メインポジション",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="maximum_ball_speed",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(175),
                ],
                verbose_name="最大球速",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="right_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="ライト適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="second_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="セカンド適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="shortstop_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="ショート適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="third_appropriate",
            field=models.CharField(
                choices=[
                    ("キャッチャー", "キャッチャー"),
                    ("ファースト", "ファースト"),
                    ("セカンド", "セカンド"),
                    ("サード", "サード"),
                    ("ショート", "ショート"),
                    ("レフト", "レフト"),
                    ("センター", "センター"),
                    ("ライト", "ライト"),
                ],
                default="◎",
                max_length=10,
                verbose_name="サード適正",
            ),
        ),
    ]
