# Generated by Django 4.1.7 on 2023-05-06 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="control_of_straight",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="ストレートのコントロール",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="growth_of_straight",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="ストレートのノビ",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="mental_strength",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(5),
                ],
                verbose_name="メンタル",
            ),
        ),
    ]
