# Generated by Django 4.1.7 on 2023-04-20 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0002_alter_player_center_appropriate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="arm_accuracy",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(1000),
                ],
                verbose_name="送球",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="arm_strength",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(1000),
                ],
                verbose_name="肩力",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="catch",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(1000),
                ],
                verbose_name="捕球精度",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="reaction",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(1000),
                ],
                verbose_name="打球反応",
            ),
        ),
    ]
