# Generated by Django 4.1.7 on 2023-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "first_version",
            "0003_remove_player_player_type_alter_player_arm_accuracy_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="pitcher_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="×",
                max_length=10,
                verbose_name="ピッチャー適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="bbox",
            field=models.CharField(
                choices=[("右", "右"), ("左", "左"), ("両", "両")],
                default="右",
                max_length=5,
                verbose_name="打席",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="throw",
            field=models.CharField(
                choices=[("右", "右"), ("左", "左"), ("両", "両")],
                default="右",
                max_length=5,
                verbose_name="利き腕",
            ),
        ),
    ]
