# Generated by Django 4.1.7 on 2023-05-08 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0004_player_pitcher_appropriate_alter_player_bbox_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="main_position",
            field=models.CharField(
                choices=[
                    ("pitcher", "ピッチャー"),
                    ("catcher", "キャッチャー"),
                    ("first", "ファースト"),
                    ("second", "セカンド"),
                    ("third", "サード"),
                    ("shortstop", "ショート"),
                    ("left", "レフト"),
                    ("center", "センター"),
                    ("right", "ライト"),
                ],
                default="pitcher",
                max_length=12,
                verbose_name="メインポジション",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="power_of_straight",
            field=models.PositiveSmallIntegerField(
                default=200,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="ストレートの球威",
            ),
        ),
    ]
