# Generated by Django 4.1.7 on 2023-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "first_version",
            "0004_alter_player_arm_accuracy_alter_player_arm_strength_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="catcher_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="キャッチャー適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="center_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="センター適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="first_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="ファースト適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="left_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="レフト適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="right_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="ライト適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="second_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="セカンド適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="shortstop_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="ショート適正",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="third_appropriate",
            field=models.CharField(
                choices=[("◎", "◎"), ("〇", "〇"), ("△", "△"), ("×", "×")],
                default="◎",
                max_length=10,
                verbose_name="サード適正",
            ),
        ),
    ]
