# Generated by Django 4.1.7 on 2023-04-22 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0006_alter_player_catcher_appropriate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.PositiveSmallIntegerField(
                default=180,
                validators=[
                    django.core.validators.MaxValueValidator(220),
                    django.core.validators.MinValueValidator(150),
                ],
                verbose_name="身長",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=80,
                validators=[
                    django.core.validators.MaxValueValidator(130),
                    django.core.validators.MinValueValidator(50),
                ],
                verbose_name="体重",
            ),
        ),
    ]
