# Generated by Django 4.1.7 on 2023-04-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0007_alter_player_height_alter_player_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="aid",
        ),
    ]
