# Generated by Django 4.1.7 on 2023-04-22 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0008_remove_player_aid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="good_cnt",
            field=models.BigIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="いいね",
            ),
        ),
    ]
