# Generated by Django 4.1.7 on 2023-05-03 05:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("first_version", "0010_player_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="created_by",
            field=models.ForeignKey(
                default=django.contrib.auth.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成ユーザー",
            ),
        ),
    ]
