# Generated by Django 4.1.7 on 2023-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0016_alter_player_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="created_by",
            field=models.CharField(max_length=15),
        ),
    ]
