# Generated by Django 4.1.7 on 2023-05-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0017_alter_player_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="created_by",
        ),
    ]
