# Generated by Django 4.1.7 on 2023-05-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_version", "0019_player_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="user",
        ),
    ]
